### ISSUE TITLE
Site error. Can't access doc site.

### ISSUE THREAD

**Issue by 0xy7d** [matnex-mix/SPHP#1]
![sphp error](https://user-images.githubusercontent.com/49034182/92787806-559f2a00-f3a1-11ea-821f-697b073e773f.PNG)

**Comment by matnex-mix** [comment]
Hi @maliex4mix4 , this is because i added my localhost db details to `config.json`

**Comment by matnex-mix** [comment]
Fixed this issue, http://getsphp.herokuapp.com now works...

**Comment by 0xy7d** [comment]
Great job :)
